default: &default
  dispatchers:
    - polling_interval: 2
      batch_size: 500
  workers:
    - queues: "ai_reports"
      threads: 2
      processes: 1
      polling_interval: 2
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
